### ISSUE TITLE
Image missing in the introduction file (workflow image)

### ISSUE THREAD

**Issue by amanmdesai** [zfit/zfit-tutorials#28]
Issue on page /tutorials/introduction/Introduction.html

**Comment by jonas-eschle** [comment]
Ah, nice catch! That's indeed a bit tricky as we fidle with the pathes, trying to fix it

**Comment by amanmdesai** [comment]
I was able to fix this in another repository by using markdown to call the image. 

Let me try that technique here.

**Comment by amanmdesai** [comment]
I think I now understand the problem: 
for the source file: https://github.com/zfit/zfit-tutorials/blob/master/introduction/Introduction.ipynb the path is ../_static/zfit_workflow.png whereas for the target file https://github.com/zfit/zfit-tutorials/blob/master/_website/tutorials/introduction/Introduction.ipynb the path is ../../../_static/zfit_workflow.png 

is that the problem?

**Comment by jonas-eschle** [comment]
Yes, that's partially the problem, thanks a lot for looking into it! It should be solved by setting the right path variable. But I am not sure that it's all there is, I am checking and should get that fixed

**Comment by amanmdesai** [comment]
how about keeping the image in the same folder as the jupyter notebook?  since there aren't many images to deal with.

**Comment by amanmdesai** [comment]
Closing the issue. The problem is solved. Thanks @jonas-eschle
